{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8549bdb7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "\n",
    "class Weather:\n",
    "    # information: city, country, latitude, longitude, temperature, elevation, windspeed, and observation time\n",
    "    def __init__(self, city, country, latitude, longitude, temperature, elevation, windspeed, observation_time):\n",
    "        # 파라미터로 받은 위 데이터를\n",
    "        # 객체속성(object attribute)에 할당\n",
    "        self.city = city\n",
    "        self.country = country\n",
    "        self.latitude = latitude\n",
    "        self.longitude = longitude\n",
    "        self.temperature = temperature\n",
    "        self.elevation = elevation\n",
    "        self.windspeed = windspeed\n",
    "        self.observation_time = observation_time\n",
    "    \n",
    "    # __str__ 함수 구현하기 \n",
    "    def __str__(self):\n",
    "        return f\"Weather in {self.city}: {self.temperature}° C\"\n",
    "\n",
    "# 4주차 교안처럼 error handling을 safe_get 방식으로 만들기\n",
    "def safe_get(url, **kwargs):\n",
    "    try:\n",
    "        # professor said good habit (1) is setting a timeout to avoid hanging)\n",
    "        user_response = requests.get(url, timeout=10, **kwargs)\n",
    "        \n",
    "        # professor said good habit (2) is ALWAYS checking \".ok\"\n",
    "        if user_response.ok:\n",
    "            return user_response.json()\n",
    "        else:\n",
    "            print(\"Failed:\", user_response.status_code)\n",
    "            return None\n",
    "        \n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(\"Network error:\", e)\n",
    "        return None\n",
    "\n",
    "def main():\n",
    "    # 교안에서 했던 것: URL, params, response, print(\"문구\", response.변수)\n",
    "    # 1. 입력값(도시 및 나라)  \n",
    "    city = \"Suwon\"\n",
    "    country = \"KR\"\n",
    "    \n",
    "    # a\n",
    "    \n",
    "    # 교안에서 URL = \"\", params = {}, response = requests.get()\n",
    "    # 2. geocoding에 맞게 URL과 params를 \n",
    "    # .json으로 parsing해서 latitude와 longitude를 받아오기\n",
    "    # https://geocoding-api.open-meteo.com/v1/search \n",
    "    # url = \" https://geocoding-api.open-meteo.com/v1/search\"\n",
    "    \n",
    "    # 변수명 url로 하면 안 되는 이유!!!\n",
    "    # url이 2개 존재하므로 -> 반드시 어떤 url인지 구분할 수 있도록 적기 \n",
    "    # 헷갈리지 않게 변수명 geocoding을 붙이기 \n",
    "    geo_url = \"https://geocoding-api.open-meteo.com/v1/search\"\n",
    "    geo_params = {\n",
    "        # Open-Meteo Geocoding API의 파라미터 그대로 name, country, count \n",
    "        \"name\": city, # name 그대로\n",
    "        \"country\": country, \n",
    "        \"count\": 1,\n",
    "    }\n",
    "    \n",
    "    # r = requests.get(URL, params={\"userId\": 2}, headers=headers, timeout=10)\n",
    "    # 위 방식을 safe_get으로 해결할 수 있음    \n",
    "    geo_data = safe_get(geo_url, params = geo_params)\n",
    "    # 결과가 없을 경우 에러핸들링 \n",
    "    if not geo_data or \"results\" not in geo_data:\n",
    "        print(\"City couldn't be found.\")\n",
    "        return \n",
    "    \n",
    "    # 필요한 데이터 꺼내기 \n",
    "    first_data = geo_data[\"results\"][0]\n",
    "    # 불러온 데이터에서 latitude, longitude 가져오기\n",
    "    latitude = first_data[\"latitude\"]\n",
    "    longitude = first_data[\"longitude\"]\n",
    "    \n",
    "    # b\n",
    "    \n",
    "    # 3. 위와 똑같은 방식으로\n",
    "    # 이번에는 weather forecast API 호출하기 \n",
    "    # https://api.open-meteo.com/v1/forecast?current_weather=true\n",
    "    weather_url = \"https://api.open-meteo.com/v1/forecast?current_weather=true\"\n",
    "    weather_params = {\n",
    "        \"latitude\": latitude,\n",
    "        \"longitude\": longitude,\n",
    "        \"current_weather\": True\n",
    "    }\n",
    "    \n",
    "    \n",
    "    # 응답을 먼저 받고나서 -> 에러 체크 -> json으로 변환하기\n",
    "    ## initial_weather_response = requests.get(weather_url, params = weather_params, timeout=10)\n",
    "    # error handling\n",
    "    ## initial_weather_response.raise_for_status() \n",
    "    # 그리고나서 json 변환 \n",
    "    ## json_weather_response = initial_weather_response.json()\n",
    "    \n",
    "    ## current_weather_response = json_weather_response['current_weather']\n",
    "    initial_weather_response = safe_get(weather_url, params = weather_params)\n",
    "    \n",
    "    if not initial_weather_response:\n",
    "        print(\"It is failed to retrieve weather data.\")\n",
    "        return \n",
    "    \n",
    "    current_weather_response = initial_weather_response['current_weather']\n",
    "    \n",
    "    # c\n",
    "    \n",
    "    # instance 만들고나서 출력 \n",
    "    user_weather = Weather(\n",
    "        # city, country, latitude, longitude, temperature, elevation, windspeed, observation_time):\n",
    "        city = city,\n",
    "        country = country,\n",
    "        latitude = latitude,\n",
    "        longitude = longitude,\n",
    "        temperature = current_weather_response['temperature'],\n",
    "        elevation = initial_weather_response['elevation'],\n",
    "        windspeed = current_weather_response['windspeed'],\n",
    "        observation_time = current_weather_response['time'],\n",
    "    )\n",
    "    \n",
    "    # print()\n",
    "    \n",
    "    print(user_weather)\n",
    "    \n",
    "    print(\"All object data: \", vars(user_weather))\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
